version: '3.8'

services:
  db:
    image: mysql:8.0.11
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shop
      MYSQL_USER: monapi
      MYSQL_PASSWORD: secure_password

  web:
    build: .
    command: dockerize -wait tcp://db:3306 -timeout 60s python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: monapi
      MYSQL_PASSWORD: secure_password
      MYSQL_DB: shop

volumes:
  mysql_data: 