# Generated by Django 5.0.4 on 2024-05-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0004_car_image_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
